// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC406QYJ4Q3sJrlckUpdMg4XO1IleUxds8',
    appId: '1:437948490343:web:cf7d32a01b072285baaac2',
    messagingSenderId: '437948490343',
    projectId: 'intenship-project-2cd80',
    authDomain: 'intenship-project-2cd80.firebaseapp.com',
    storageBucket: 'intenship-project-2cd80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhpx8lZWoU6Xh-VjAG-irLR9P0_QqwtCk',
    appId: '1:437948490343:android:1ba49862cc0c81d1baaac2',
    messagingSenderId: '437948490343',
    projectId: 'intenship-project-2cd80',
    storageBucket: 'intenship-project-2cd80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQVPKoFZLmFLRN64n2SfIrxlsFGIDZsg',
    appId: '1:437948490343:ios:09bcfef8c3264e67baaac2',
    messagingSenderId: '437948490343',
    projectId: 'intenship-project-2cd80',
    storageBucket: 'intenship-project-2cd80.appspot.com',
    iosBundleId: 'com.example.internshipProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC406QYJ4Q3sJrlckUpdMg4XO1IleUxds8',
    appId: '1:437948490343:web:176883bc11629501baaac2',
    messagingSenderId: '437948490343',
    projectId: 'intenship-project-2cd80',
    authDomain: 'intenship-project-2cd80.firebaseapp.com',
    storageBucket: 'intenship-project-2cd80.appspot.com',
  );
}
